# Generated by Django 4.0.2 on 2022-02-24 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('email', 'email'), ('sms', 'sms')], default='email', max_length=32)),
                ('sender', models.EmailField(max_length=254)),
                ('msg', models.CharField(max_length=254)),
            ],
        ),
    ]
