# Generated by Django 4.0.2 on 2022-02-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nortifications', '0002_notif_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notif',
            name='type',
            field=models.CharField(choices=[('email', 'email'), ('sms', 'sms'), ('push', 'push')], default='email', max_length=32),
        ),
    ]
